# Generated by Django 4.2.2 on 2023-07-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinearAlgebra', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matrix',
            new_name='MatrixStore',
        ),
    ]
