# Generated by Django 4.2.2 on 2023-07-04 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LinearAlgebra', '0002_rename_matrix_matrixstore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrixstore',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='matrixstore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
